### ISSUE TITLE
Botania Floral Powder

### ISSUE THREAD

**Issue by DarkestStryke** [Y0ungSandwich/Mech-Magic-1.12.2#13]
Unable to craft the following ingame on a server, works in single player.

Floral Light Blue powder - From mystical light blue petals, or blue Orchids
Floral Orange Power - From mystical orange petals, or orange tulips
Floral Pink Powder - From mystical pink petals
Floral Red Powder - From red Petals, or poppys
Floral Light Grey Powder - From light grey petals, or Azure Bluet
Floral Yellow Powder - From Yellow petals, or dandelions

No item appears in the output window if done in the personal crafting grid, if tried in modded crafting options, output sometimes appears, but you can't take it out.

**Comment by Y0ungSandwich** [comment]
linked to #12 (most likely)
