### ISSUE TITLE
Advanced Generator's control curcuit not able to be made

### ISSUE THREAD

**Issue by Kamizura** [Y0ungSandwich/Mech-Magic-1.12.2#19]
tried to make a control curcuit, the recipe was correct in JEI but no item was showing to complete the craft 
![2018-01-07_19 42 08](https://user-images.githubusercontent.com/34008956/34653411-40d12fc6-f3e3-11e7-8c4b-2c6690183628.png)

![2018-01-07_19 42 11](https://user-images.githubusercontent.com/34008956/34653414-492f0daa-f3e3-11e7-8b70-4771d357833e.png)

the two recipe's match but cant actually make it..

**Comment by Y0ungSandwich** [comment]
Work on single player?

**Comment by Kamizura** [comment]
just tried that now, yes it works on single player
