### ISSUE TITLE
Twilight Forest - Hydra Not Spawning Correctly

### ISSUE THREAD

**Issue by MorHunter** [Y0ungSandwich/Mech-Magic-1.12.2#21]
On The Official Server when you find a Hydra, it spawns without a body, and the heads are stationary. The first one I found didn't have necks though the second one did, but they looked like they were being damaged. You can not damage the heads. I'm including 2 screenshots of the second one I found.
![2018-01-09_18 16 00](https://user-images.githubusercontent.com/35280692/34751821-06b60796-f56c-11e7-90ca-f6b400a95ced.png)
![2018-01-09_18 24 40](https://user-images.githubusercontent.com/35280692/34751825-0b97111a-f56c-11e7-8d99-b05d5994b548.png)

**Comment by Y0ungSandwich** [comment]
No need to report server side issues here unless they are confirmed to have the same result in a single player world.

**Comment by Y0ungSandwich** [comment]
This should be fixed in 2.0.4
