### ISSUE TITLE
Immersive Engineering: Steel ingots

### ISSUE THREAD

**Issue by Ibrahim228** [Y0ungSandwich/Mech-Magic-1.12.2#27]
With the last update (thanks for updating though :) ) neither Crude Blast Furnace or Improved Blast Furnace doesn't smelt iron ingots to steel ingots. Maybe conflicts with steel ingots from the other mods?
![iesteel](https://user-images.githubusercontent.com/36858569/36688514-84e74fc8-1b4e-11e8-9e18-8ad4ed4cca3c.png)

**Comment by Y0ungSandwich** [comment]
And this was working before this recent update?

Is this on a server or single player?

**Comment by Ibrahim228** [comment]
Yes, it was working on 2.0.5 with IE 0.12-76.
The issue appears in single player. Didn't test on server though.

**Comment by Y0ungSandwich** [comment]
Seems to be noted and fixed for the next build of IE
https://github.com/BluSunrize/ImmersiveEngineering/issues/2823
