### ISSUE TITLE
Shared inventory on singleplayer

### ISSUE THREAD

**Issue by DragaoNimhe** [Y0ungSandwich/Mech-Magic-1.12.2#3]
Hey, not sure if this is maybe because of the whitelist on the modpack download rn, but when my boyfriend logs into my singleplayer world his inventory is the same as mine, and vice versa.

**Comment by Y0ungSandwich** [comment]
Starting Inventory. Its configured that way :)

**Comment by Y0ungSandwich** [comment]
1.12.2 bug from Mojang
