### ISSUE TITLE
Healthbar bug with Vampirism and Cyclic

### ISSUE THREAD

**Issue by DragaoNimhe** [Y0ungSandwich/Mech-Magic-1.12.2#32]
When you eat a Cyclic Heart Container or gain extra hearts via the Vampirism mod, then teleport to another dimension (such as the end/nether), the entire health bar will flash as if it is constantly regenerating hearts. When it is just Cyclic hearts (no vampirism status), this also makes you lose hunger as if you are constantly regenerating health. The issue does not persist with Scaling Health heart containers.

**Comment by Y0ungSandwich** [comment]
Fixed half of this with cyclic. Need to look into methods of fixing via vampirism.
