### ISSUE TITLE
Tombstones and keys vanishing

### ISSUE THREAD

**Issue by DragaoNimhe** [Y0ungSandwich/Mech-Magic-1.12.2#33]
I have had multiple players have issues with keys vanishing, leaving them unable to access their graves, as well as a few instances of graves vanishing. In the most recent case of this, the grave vanished upon creation of a second grave. I have not been able to personally replicate this through testing, so I am unsure why it's happening.

**Comment by Y0ungSandwich** [comment]
Haven't seen it myself either but I'll keep an eye out.

**Comment by DragaoNimhe** [comment]
I have now personally witnessed this event happening twice. I have set keepinventory to true on our server until a fix is found, as it is happening frequently enough to upset our beta testers greatly. Both instances, i watched the person die (Room and a staff member on our server), they were in a wilderness area, no claims present, on an open block (grass, surface) with no obstructions. No errors occurred in console at the time of their death.

**Comment by Y0ungSandwich** [comment]
And none of your protection plugins limit out of claim or in wild building?

**Comment by DragaoNimhe** [comment]
No they do not.

Here's our region info for that world (UniverseGuard 2):
https://i.imgur.com/wDCtNKj.png

Here's our flaglist for wild (Griefprevention):
default-wilderness {
            block-break=true
            block-place=true
            collide-block=true
            collide-entity=true
            command-execute=true
            command-execute-pvp=true
            enter-claim=true
            entity-damage=true
            entity-riding=true
            entity-spawn=true
            entity-teleport-from=true
            entity-teleport-to=true
            exit-claim=true
            explosion=true
            explosion-surface=true
            fire-spread=false
            interact-block-primary=true
            interact-block-secondary=true
            interact-entity-primary=true
            interact-entity-secondary=true
            interact-inventory=true
            interact-inventory-click=true
            interact-item-primary=true
            interact-item-secondary=true
            item-drop=true
            item-pickup=true
            item-spawn=true
            item-use=true
            liquid-flow=true
            portal-use=true
            projectile-impact-block=true
            projectile-impact-entity=true

**Comment by Y0ungSandwich** [comment]
Confirmed Grief Prevention.
