### ISSUE TITLE
Issue with Inventory Upgrades and Graves

### ISSUE THREAD

**Issue by DragaoNimhe** [Y0ungSandwich/Mech-Magic-1.12.2#34]
When someone dies after having eaten an inventory upgrade cake, the items that were in the upgraded portion of their inventory do not spawn in a grave. If they only had items in the upgraded portion of their inventory, no grave will spawn at all.

**Comment by Y0ungSandwich** [comment]
This is most likely some issue with mod compatible and limit of storage in the grave. I'll mention it to the author.

**Comment by Y0ungSandwich** [comment]
Inventory Upgrades do not persist through death. Eating another upgrade will unlock the inventory again with the items that were in it before death.
