### ISSUE TITLE
Server crashes when certain villages are loaded

### ISSUE THREAD

**Issue by DragaoNimhe** [Y0ungSandwich/Mech-Magic-1.12.2#35]
Single crash report remaining:

https://pastebin.com/cuCPf89L

**Comment by Y0ungSandwich** [comment]
This could be similar to an old issue we had where modded entities were turning villagers into zombies. I'll check em out to day.

**Comment by DragaoNimhe** [comment]
The shorter of the two crash logs was caused by an older version of UniverseGuard. Testing latest release shortly to see if the issue persists.

The longer of the two crash logs still remains unsolved. Have loaded server without any plugins, on sponge 3064, forge 2655, with default (server download) config, and it still crashes.

The most baffling thing is that the crashes are seemingly random. They have happened in as little as 15 seconds after loading the area, but then sometimes take up to 15 minutes before they occur. I have been standing in the exact same spot throughout all testing.

**Comment by Y0ungSandwich** [comment]
Can you delete the crash report thats no longer needed?

**Comment by DragaoNimhe** [comment]
Done

**Comment by DragaoNimhe** [comment]
Fixed - was some sort of corrupt worldgen issue.
