### ISSUE TITLE
issue with thaumcraft not specifying which vis crystals are needed for some segments in the book

### ISSUE THREAD

**Issue by Kamizura** [Y0ungSandwich/Mech-Magic-1.12.2#37]
currently in the thaumonomicon, a few things that requires vis crystals to complete research fails because it cant tell which crystal is needed (like arcane bellows and essentia smelting) since they all look the same and have "thaumcraft" under the vis crystal instead of the one it needs, i found the fix here: https://github.com/Azanor/thaumcraft-beta/issues/511

**Comment by Y0ungSandwich** [comment]
Did anyone ever look into this in the current version of the pack?
