### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by redaktiv** [Y0ungSandwich/Mech-Magic-1.12.2#45]
Single player world

[https://pastebin.com/Z4zvwAJV](https://pastebin.com/Z4zvwAJV)

**Comment by Y0ungSandwich** [comment]
Bad link

**Comment by redaktiv** [comment]
I've fixed the link.

**Comment by Y0ungSandwich** [comment]
Is this a freshly generated world or an established world?

**Comment by redaktiv** [comment]
It is an established world (The one I was playing when you visit my stream on Twitch). It dosen't happend the first time I load the world but if I exit the world and load it again it crashes when actually addition auto-breaker tries to break a block.

**Comment by Y0ungSandwich** [comment]
Is it a specific block that gets put in front of it or is it something sort of random block each time.

**Comment by redaktiv** [comment]
It is a random block. auto-placer puts a stone block. Lens of the miner makes it into random ore block and then the auto-breaker breaks the block.

**Comment by Y0ungSandwich** [comment]
You could try removing ftbutils for a short time fix until I report it to the mod author.
