### ISSUE TITLE
Crash Log Mech and Magic 1.12.2 Beta

### ISSUE THREAD

**Issue by Preacher85** [Y0ungSandwich/Mech-Magic-1.12.2#5]
Weve been messing around with 1.12.2 beta and continually hit this crash.  Ive got several copies of them.  

[crash-2017-11-02_20.46.58-server.txt](https://github.com/Y0ungSandwich/Mech-Magic-1.12.2/files/1441895/crash-2017-11-02_20.46.58-server.txt)

Every crash log seems to indicate a piece of random gear equipped on a mob in the game world, with protect.all attached to it.  Seems to happen at random.

**Comment by Y0ungSandwich** [comment]
Remove Sponge and try to reproduce

**Comment by Preacher85** [comment]
Removing Sponge seems to have fixed the issue.  Sadly, we can't remove sponge from the world data, and must restart a new world.  Thank you for your assistance in the matter.

**Comment by Y0ungSandwich** [comment]
Well if its a mob simply start the server in peaceful to remove all mobs and then turn it back to whatever your normal difficulty is. @Preacher85 

At this time I am not stressing over Sponge compatibility but it will be looked into more later for servers that still wish to use that over the FTBUtilities options we will provide.
