### ISSUE TITLE
bouble items dissapierd 

### ISSUE THREAD

**Issue by DreamzOfDeath** [Y0ungSandwich/Mech-Magic-1.12.2#53]
i was in the twilight forest fighting the litch king and dueing in the fight my chaos gem flight gave in and i tryed to go back into flight mode and it was not letting me. so i moved away from the boss and the fight to see if the gem was deaceivated but it seem that my items that were in the bouble tab have gone. i had the chaos gem with fight, refind chaos orb, twilight cloak and climbing glove.

**Comment by Y0ungSandwich** [comment]
Seems to be an issue with graves not storing baubles information since it's not technically in the inventory. We're investigating alternative grave mods with baubles integration.

**Comment by DreamzOfDeath** [comment]
i did not die during the fight so i dont know if it is to do with the graves

**Comment by Y0ungSandwich** [comment]
Chances are they we're gone before the fight from a previous death. Had the same happen to mine.

**Comment by DreamzOfDeath** [comment]
huh odd then that only those items vanshed and not my tools or wepons i had on my at the time

**Comment by Y0ungSandwich** [comment]
We're they in your inventory or in your baubles slots?

**Comment by DreamzOfDeath** [comment]
chaos gem, refind chaos orb, twilight cloak and climbing glove were in the baubles slots that vanshed, the rest of my items like sword, axe, pickaxe were still in my inventory

**Comment by Y0ungSandwich** [comment]
Yeah exactly what I said. Baubles slots are not really inventory slots. The openblocks graves simply don't support baubles. Anything in your actually inventory would be fine.
