### ISSUE TITLE
thaumcraft Arcane bore crashing game

### ISSUE THREAD

**Issue by TheIcyCreeper** [Y0ungSandwich/Mech-Magic-1.12.2#59]
https://paste.atlauncher.com/view/8e273820
i have tried it a few times now whenever i turn it on my game stops responding and i have to kill minecraft and relaunch it and the world then becomes impossible to use as every time i go into it the game stops responding

**Comment by Y0ungSandwich** [comment]
This is on single player?

**Comment by TheIcyCreeper** [comment]
ye
