### ISSUE TITLE
Grains of Infinity not spawning on server

### ISSUE THREAD

**Issue by BigDen4** [Y0ungSandwich/Mech-Magic-1.12.2#60]
Grains of Infinity seem to not spawn when setting Bedrock on fire, which is the only way I know how you can gain it. I'm using a flint and steel on bedrock, I can hear the sound clip that tells you that a grain has pop out but their is nothing there. I did a test in single player and it is dropping, so this is only affecting the server

**Comment by Y0ungSandwich** [comment]
Server issues do not go on GitHub
