### ISSUE TITLE
Very low TPS on server

### ISSUE THREAD

**Issue by StealthyKamereon** [Y0ungSandwich/Mech-Magic-1.12.2#61]
Hi,
I'm playing this pack on a server and we've been experiencing very low tps since the beginning (around 15 to 10 tps). There was no much to lag about so we just thought it was the server provider. But after talking a bit with the server provider, it seems that it's not from his side... After a bit of investigation, the TPS are fine when there is only one player on the server or several player in the same spot but as soon as the server has to load different area, the TPS are dropping (to between 1 and 10).
In the logs I made some profile commands, I was alone and the TPS were already around 17.
Here are the logs :
[latest.log](https://github.com/Y0ungSandwich/Mech-Magic-1.12.2/files/2205137/latest.1.log)

Thank you in advance for your support :)

**Comment by Y0ungSandwich** [comment]
If TPS is low it's indeed your host at some level. Wether that's you not having purchased a package with enough RAM or the host machine being bottlenecked. A pack naturally just doesn't drop TPS unless you have some sloppy setups that are causing the lag. I.e. clogged Build craft pipes, items spewing out of pipes and inventories, fast growing farms, etc

**Comment by StealthyKamereon** [comment]
Yeah that what I thought. I'll see with them, thank you for your help :)
