### ISSUE TITLE
Duplication Bug - Blood Magic - Buckets of LIfe Essence

### ISSUE THREAD

**Issue by Banjooie** [Y0ungSandwich/Mech-Magic-1.12.2#62]
**Describe the bug**

Disregard Bitches, Acquire Buckets: A Musical
1: Take a blood altar, and plug a hopper into the side of it. Vanilla hopper will do.
2: Ensure there is enough blood in the altar for N buckets, where N is 'at least one more than free spaces in your inventory'. 'Enough Blood' is N*1000.
3: Place N buckets into the altar, and then wait for a while until it's finished. 
4: With an empty space in your hotbar, retrieve the bucket. Your inventory is about to fill with buckets..
5: Minus a small pile of buckets on the ground. Clear one more space in your inventory.
6: Within that one spot in your inventory is a stack of N buckets. You now have N + N - 1 buckets.

**Crash Report or Log**
Well, it didn't crash, friend, so...

**Expected behavior**
I put in N buckets. I expected to retrieve N buckets, but instead retrieved N + N - 1 buckets. This is too many buckets.

**Screenshots**
https://puu.sh/B5ujp/40834c560f.png
See that stack of 11 filled buckets? You aren't supposed to be even able to do that with buckets.

**Additional context**
I'm sorry Rach D:

**Comment by Y0ungSandwich** [comment]
While I could do without the silliness I do appreciate someone actually using the issue template lol. Do you have a screenshot of your setup instead of the items duped?

**Comment by Banjooie** [comment]
https://i.imgur.com/nc22tQC.png
I apologize for having accidentally exposed you to humour.
