### ISSUE TITLE
Cyclic Wireless Transporting and Thaumcraft

### ISSUE THREAD

**Issue by NicBOMB** [Y0ungSandwich/Mech-Magic-1.12.2#66]
**Describe the bug**
Sending apples with cyclic wireless transport to a Thaumium Essentia Smeltery causes crashing on singleplayer and server (client-side crash).

**Crash Report or Log**
Singleplayer:
https://cdn.discordapp.com/attachments/478065771352948756/493559232915046441/crash-2018-09-23_16.07.54-client.txt
https://cdn.discordapp.com/attachments/478065771352948756/493559229316202498/crash-2018-09-23_16.07.34-server.txt
Connected to Server:
https://cdn.discordapp.com/attachments/478065771352948756/493557706393649152/crash-2018-09-23_15.59.58-client.txt

**Expected behavior**
The apples would be sent to the top slot of a thaumium smeltery and be burnt down into herba and victus. The golems are too stupid to put items in the right slots, so cyclic was my first option, given it worked so well in the past.

**Screenshots**
Can't login. Get instantly disconnected.

**Additional context**
The apples must still be trying to get sent to my thaumium smeltery if I crash on login.

**Comment by Y0ungSandwich** [comment]
I will contact the author of cyclic and see what he thinks.  Is this on our server?

**Comment by ghost** [comment]
> I will contact the author of cyclic and see what he thinks. Is this on our server?

It is not on the official server. The other server (SurvivalQuest mm.survivalquest.net) is running 
MM 3.0.11 and still has this problem.
