### ISSUE TITLE
Ender Teleport Not Working

### ISSUE THREAD

**Issue by Kaziri** [Y0ungSandwich/Mech-Magic-1.12.2#67]
Probably a Config Issue on my end but I never editted configs so I do not know where to change this but whenever I attempt to use the ender book or Monk blink skill or even use a basic ender pearl I get the particles but no actual Teleportation, I remain in the place i activated the effect, when Googling this issue, all I get are Bukkit fixes with plugins and such, any help would be appreciated, I noticed the issue on version 3.0.5-1 and i updated to 3.0.8 but still have the same issues

**Comment by Y0ungSandwich** [comment]
Is this on a single player world or on a server?

**Comment by Kaziri** [comment]
It is on a server, though a small one of just myself and my brother

**Comment by Y0ungSandwich** [comment]
No special plugins or anything just a basic server?
Can you reproduce the issue on single player?

**Comment by Kaziri** [comment]
Just tested in single player and it all works just fine, looks like it's only in multiplayer, and no, no special plugins, just the basic server you get when you click "create a server" on the ATLauncher although I have 3 extra mods added in, but they were never a problem before, and they work just fine in single player, I deleted my last world then made a new one and that's when the trouble started but both worlds had the same mods and were both on 3.0.5-1
