### ISSUE TITLE
Am having a singleplayer Lan game crash after using a waypoint stone

### ISSUE THREAD

**Issue by Natchel93** [Y0ungSandwich/Mech-Magic-1.12.2#7]
https://pastebin.com/cdM0DSuZ

The title says it all, though me and my friend did add Pam's Harvestcraft to the game because he likes the mod alot, we werent having problems with it at all.

Just a fair warning. If it is that then its on me :D

**Comment by Y0ungSandwich** [comment]
Is it crashing on world load now or just when you interact with the waystone?

**Comment by Natchel93** [comment]
Its now just crashing on load in.
things start loading and ive seen a villager before but it just crashes the game.
