### ISSUE TITLE
Server ejects players after signin, but worked fine for the last two weeks or so.

### ISSUE THREAD

**Issue by azulskyknight** [Y0ungSandwich/Mech-Magic-1.12.2#72]
I honestly am not sure what's going on here.  But, I have a world built in v3.0.26, all default options via ATLauncher.  The server ran flawlessly for almost two weeks.  Late last night about this time, I signed out of the server, all was well.

Terrific pack by the way!

Anyway, this afternoon I got home from work and my friends found me on discord and asked me what was wrong with the server.  This came as a surprise to me.  I signed in, and it worked fine.  Then one friend signed in, and both clients froze.  The server, kept operating.  I could issue commands.  But, after some time, the clients timed out, and associated player left messages appeared on the server's console.

We tried reinstalling our clients.
I tried building a fresh new Mech & Magic world with a new seed.
We even updated the OpenJDK v8 64bit runtimes.  Yet the behavior persists, server loads fine, someone logs in and immediately lags out.
Everything got restarted at least once too for good measure.

I apologize for not providing pastebin links to latest.log, but they are far too large to work on that service.  So instead, I've put the .log files into a Google drive.  

Here is the old server that ran wonderfully for two weeks or so: https://drive.google.com/file/d/15GAAGFz3y84lEaLDapk9MSqz9grBj38_/view?usp=sharing

Here is the fresh new instance I created trying to troubleshoot:  https://drive.google.com/file/d/15rV13Imih0vw1Q0eyPjxUNom5iwI3U3m/view?usp=sharing

I gave up on Mech & Magic, and restarted our previous Resonant Rise instance on the same platform, and off it went.  I'm hoping someone knows something, because honestly we'd like to get back to this pack, it's far more entertaining.

**Comment by deanmsands3** [comment]
The recommended workaround on the Mech and Magic Discord is to use the Twitch Launcher instead. I honestly don't know why this works but it does.

**Comment by azulskyknight** [comment]
Thanks for that, but do I do this on the client or the server? or both?

*Edit* It seems using the client to connect to the original server works, but it's just me at the moment.  Thanks for the suggestion at least I have something to tinker with.

**Comment by Y0ungSandwich** [comment]
We are checking into it now on the ATLauncher side.

**Comment by azulskyknight** [comment]
Thank you, I've got some more data as well.  I was able to launch the AT Launcher built server, and connect to it via a Twitch provided client.  

After doing that I noticed that the twitch client only has JourneyMaps as a client mod, so I modified my AT Launcher client to match.  I was able to connect, but moving north of my home position resulted in the usual time out on the client side.  

I further located the runtime used by the twitch client, and configured AT launcher to use that official java runtime as opposed to OpenJRE 8.0.222.10 x64.  Sadly, this resulted in the same crash of the client.  Swapping back to the Twitch client seems to work.

So I'm currently working with a Twitch client, and an ATLauncher server.  The ATLauncher server is running the above OpenJRE runtime, and the client is the official Java 8 downloaded by the minecraft launcher.  

UI Tweaks is missing, so inventory sorting is gone.  But it's at least playable, my only real complains is the Twitch client doesn't seem to want to save my 6GB RAM setting for the client, so I have to keep editing the thing to get enough RAM to load.  

But it does indeed work... why... I'm not so sure of.  If I get some more time this afternoon I may attempt the Twitch client on OpenJRE to see if the runtime matters.

I think it's pretty safe to say this is a client side issue.

Here is a latest.log from a locking client, if that helps: https://drive.google.com/file/d/1-tYJQ-CfedyDfqpiTl6glyLYU4OEL17W/view?usp=sharing

**Comment by RyanTheAllmighty** [comment]
So I've narrowed this down to being an issue with the way ATLauncher changed the way it logs things.

I noticed when joining the official pack server, that I would lock up and the ATLauncher console would take up large amounts of cpu and memory. Once I killed the ATLauncher console process, the game immediately loaded back in.

Seems to be caused by https://github.com/MineMaarten/Signals/issues/101 which causes mass client side logs (from what I can tell, an NPE is thrown every tick) which causes 10's of MB per minute of logs to be written, which combined with the new logging mechanism caused some issues with the launcher hanging and disconnecting.

I've now switched the logging to use a queuing mechanism that it was pre 3.3.0.0 update, and those locks are now gone when I join the official server.

The game was locking up due to the logging process, which would make it time out network requests to the servers.

I'll be releasing version 3.3.0.3 of the launcher with this change in the next couple hours which should fix this

**Comment by azulskyknight** [comment]
I can confirm killing the ATLauncher console allowed for several hours of perfect operation with my original client settings.  All save, the updated version of OpenJRE.  Several other players on my server have also met with similar success.  Very well done!  Thank you!

**Comment by RyanTheAllmighty** [comment]
This was a very odd issue, thankfully it was a simple solution. Been a bit delayed pushing the fix, I'll post a comment once it's out

**Comment by Y0ungSandwich** [comment]
I'm starting an update right now to remove Signals as well as update any mods that need updating and some file work.  Thanks for the hlep Ryan!

**Comment by azulskyknight** [comment]
I've got a new odd twist on this issue...

AT Launcher clients without the console process running, connect and worked fine.  Hours went by... then one new person showed up.  Everyone using the AT Launcher clients immediately lagged out, shortly there after the server actually crashed.  After I got the server going again, everyone started filtering back in.  

But the AT Launcher issue persists, this one specific user connects with his Twitch client, and anyone on the server using an AT Launcher client vanishes.

Here's a latest.log from one of the detonating clients.  Again, console process has been killed.

https://drive.google.com/file/d/1CUWjfIFHB4OK-9JSvZKEvND50-w5zFpg/view?usp=sharing

Meanwhile the specific player that joined that causes this?  He's not crashed once, aside when the server went and took all 7 of us with it.

**Comment by Y0ungSandwich** [comment]
There has been no update to the pack or the ATLauncher yet so the issue will of course persist for the moment. 

I am more interested in seeing the logs or crash report from the actual server at time of crash.

**Comment by azulskyknight** [comment]
Wish granted!

https://drive.google.com/file/d/1RFS4wnGHR7guFcZyMy9AMgPsLUnicHHa/view?usp=sharing

Server logs from this morning when the poor thing fell over.

**Comment by RyanTheAllmighty** [comment]
Version 3.3.0.3 of ATLauncher has gone out now with the fix for the log issue

**Comment by azulskyknight** [comment]
Well I say stick a fork in it because this one is done!

I've had 3-4 people on my server all day, no complaints and no crashes.  I intentionally left my client up pretty much 100% of the time from your report 16 hours ago until now, typically something in java goes nuts by now but not even that happened.

Literally all day in Minecraft without a single crash, a rare and wonderful thing.

**Comment by Y0ungSandwich** [comment]
Glad to hear it! Let us know if you have any more issues. Thanks for all the assistance Ryan.
