### ISSUE TITLE
server mech and magic lite mods not responding  

### ISSUE THREAD

**Issue by ghost** [Y0ungSandwich/Mech-Magic-1.12.2#74]
hi, 

so i made a server on mech and magic lite for me and me friends on version 1.12.2 and after i installed the server with the at laucher i booted op the server. but wheen i try to do anything with tinkers it just disapears, could somebody help me? i also tried with hidden redstone in creative but same issue. 

thx in advance

**Comment by Y0ungSandwich** [comment]
Provide some logs please

**Comment by ghost** [comment]
in the logs it says not found: (most major mods)
[debug.log](https://github.com/Y0ungSandwich/Mech-Magic-1.12.2/files/3534059/debug.log)

**Comment by Y0ungSandwich** [comment]
I don't want a debug file I would like the actual logs.
