### ISSUE TITLE
RFTools Spawners do not accept any form of living matter

### ISSUE THREAD

**Issue by TNT3530** [Y0ungSandwich/Mech-Magic-1.12.2#77]
**IF THIS IS AN ISSUE REGARDING THE OFFICIAL SERVER DO NOT POST HERE. BRING IT TO DISCORD**

**Describe the bug**
RFTools Spawners do not accept any form of living matter

**Crash Report or Log**
N/A

**Expected behavior**
Matter Beamers should consume the items and fill the Spawner's inventory

**Screenshots**
None

**Additional context**
https://ftbwiki.org/Spawner
The docs on what should all work, though I havent tried them all

**Comment by Zunhed** [comment]
after doing some research on this, i found that reason this its happening is cause of an bugged config file when the mod was updated. 

To solve this issue the configfile for rftools needs to be removed and then restart the game so it can generate a new config file for the mod, if playing on a sever then the config file needs to be removed on both server and client side.

Same type of issue
https://github.com/McJtyMods/RFTools/issues/1943
