### ISSUE TITLE
No Mobs/NPCs Spawning in the released 1.12.2 version

### ISSUE THREAD

**Issue by preflora** [Y0ungSandwich/Mech-Magic-1.12.2#8]
Hi we tried to start a server with this new updated version from today, and some of us had tried the beta versions in single-player with no problems. When we tried to start tonight we noticed there weren't any mobs anywhere or npcs. I then tried to start a singleplayer world with no mobs in it either. I tried to spawn cows with spawn eggs and I would hear the sound but not see or interact with them. The server owner tried to do the command to allow mobs to spawn and it didn't change anything.
We were really excited to start this mudpack so I hope we can get this fixed!
Thanks

**Comment by Y0ungSandwich** [comment]
Getting this widely this morning.  I'll look into it as soon as I can! Thanks.

**Comment by Y0ungSandwich** [comment]
https://github.com/rwtema/extrautilities/issues/1766
