### ISSUE TITLE
Twitch Launcher & Server file are missing FTB Util

### ISSUE THREAD

**Issue by Locomotivers** [Y0ungSandwich/Mech-Magic-1.12.2#82]
**IF THIS IS AN ISSUE REGARDING THE OFFICIAL SERVER DO NOT POST HERE. BRING IT TO DISCORD**

**Describe the bug**

Twitch client and server file of pack version 3.1.4 is missing the latest FTB Utilities. The server file has an older version  (FTBUtilities-5.4.0.120.jar) and not sure if it is intended since patch note indicated it is using the latest version (5.4.0.124).

**Expected behavior**
FTBUtilities-5.4.0.124.jar should be in both client & server file but it's missing

**Screenshots**

![image](https://user-images.githubusercontent.com/7984445/71540694-e7522e80-291b-11ea-9f2b-943f1f4c330a.png)
![image](https://user-images.githubusercontent.com/7984445/71540696-ed480f80-291b-11ea-9a23-85f5caed0adf.png)

**Additional context**
*Workaround suggestion*
As pack owner suggested on discord, unlock the pack in twitch and install FTBUtilities manually. If you are a server owner like me download FTBUtilities 5.4.0.120 for the client to avoid possible version diff conflict.

**Comment by Y0ungSandwich** [comment]
Look for version 3.1.4Hf on the Twitch App
All files cross with servers or clients running 3.1.4 on ATLauncher. 

Thank you
