### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by azulskyknight** [Y0ungSandwich/Mech-Magic-1.12.2#83]
Playing a world that was generated with 3.1.4 via ATLauncher.  I noticed a 3.1.5 was available, so I created a new server with 3.1.5.  Copied over the world folder, server.properties, and ops.json, and eula.txt into the new instance from my 3.1.4 instance.

Started server, and all was well.  I had multiple people connected after the update and everything seemed happy.  After several hours of happy players, I deleted my 3.1.4 instance and moved on.

So fast forward to about half an hour ago, I connect to the server and I notice in the chat box in my game client, the Vampirism mod is asking me to run the /resetBalance command.  So I run it, and it then asks me to restart minecraft.  Not knowing if it was referencing the server, or the client I restarted both.  The client restarted, the server... not so much.  I issued a stop command at the console, it terminated gracefully and I restarted it with LaunchServer.bat like I usually do.

To rule out some sort of server configuration script corruption, I renamed the instance folder, redownloaded 3.1.5 again via ATLauncher, and once again copied over my world folder, server.properties, ops.json and eula.txt.  Sadly, the server still crashes, before any player can connect to it.

Any suggestions to save this world would be nice, I'd hate to lose it we were just getting into the really fun stuff and the city we had going was turning out quite nice.

Crash report here: https://pastebin.com/e5ehFedW
Latest Log here: https://pastebin.com/ZUBq0gtq

P.S. On 3.1.4 we also experienced the bug with Aluminum blocks breaking down into the wrong ingots in shaped crafting.  Instead of OreGen, they were from Silent's Gems.  I worked around the issue by running them through a metal press from Immersive Engineering with the plate press installed.  This converted the ingots into plates, which I was then able to melt in the Smeltery and run out the ingot cast.  The ingot cast would produce the correct ingots.  But if we ever combined those ingots into a block, and tried to break them down again back into the press they'd have to go.  I never got the chance to see if this behavior continued in 3.1.5.

**Comment by Y0ungSandwich** [comment]
Well your method of updating is odd. I would never advise moving a world folder. Simply move over the mods, configs, and scripts folder like noted in all of our changelogs. This is the safest bet. 

Vampirism messaged could have been ignored. If we did anything to warrant the reset we would of forced it in the update. 

Definitely a chunk issue. I see you are running the server on 2GB of RAM? I'm not even sure how you are doing that. But anyways...lets try to easiest thing first and go into configs -> forge -> 

```
 # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false
```
change to 

```
 # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true
```

**Comment by azulskyknight** [comment]
Thanks for the suggestion but it seems I've been overruled.  Everyone but me seems happy to just reuse the seed and start over.  So, that's what I did.  The server runs just as well on 2gb (default ATLauncher setting for the server BTW) as it does with 16gb.  The client?  Yeah, that needs gobs of ram at least 6gb of it, but the server?  It needs nothing.

But that brings up another minor issue.  Immersive Engineering's Assembler can't make planks out of any of the stock minecraft logs.  Oak Wood, Spruce Wood, Birch Wood, Acacia Wood, or Jungle Wood.  It'll accept the recipe, but it just won't do it.  

But, Thaumcraft wood (Greatwood and Silverwood) turns to planks near instantly.  This is important because hand crafting treated wood planks by hand is a giant pain the rear.  Of course, Greatwood + Lumber Axe = easy farm so it's not the end of the world.  But the consistency of this makes me think it's a general setting of some sort and not a bug.

**Comment by Y0ungSandwich** [comment]
I promise the server will eventually need more than 2GB at some point. Default ATL settings mean nothing. They are defaulted like that across every modpack. We have no control over the default scripts.
