### ISSUE TITLE
Mech & Magic Vampirism 

### ISSUE THREAD

**Issue by erose9980** [Y0ungSandwich/Mech-Magic-1.12.2#87]
When Playing the game I was turned into a vampire, I have looked up how to drink blood standing by a cow the fangs show up I press v and right click on the animal and I don't get any blood, nothing happens. Now that I was turned into a vampire and i cant drink blood I die constantly loosing everything I have.  I would like this to be fixed so that I can play the game without dying all of the time. I have tried v, v right click, v left click, eating raw meat, v on any animal and villager. I have tried everything I can think of and nothing happens. I was turned by another vampire in the game. I am playing on ATLauncher with the most up to date version of Mech & Magic (3.1.8)

**Comment by Y0ungSandwich** [comment]
Did you happen to ever check your keyboards? Assign a different key to bite.
